### ISSUE TITLE
DH Imprison (#217832) not being tracked. It's in the DR List with the correct ID.

### ISSUE THREAD

**Issue by denumerable** [wardz/Diminish#10]

**Comment by wardz** [comment]
Is there some kind of new talent or covenant ability in Shadowlands that modifies it?

**Comment by denumerable** [comment]
I actually just confirmed with my previous stream that it is showing up correctly on enemy players in Battlegrounds but not on PvE mobs -- the stun DR shows up correctly on PvE mobs.

**Comment by denumerable** [comment]
I'll grab two highlights from a stream for you to view, real quick. Thanks @wardz.

**Comment by denumerable** [comment]
https://www.twitch.tv/videos/903222672 => Not showing on an NPC mob. Stuns show correctly.

https://www.twitch.tv/videos/903224976 => Correctly displaying the Imprison DR in BGs.*

*might still be processing this highlight.

**Comment by denumerable** [comment]
To be clear, I've tested with and without the PvP talent. PvP talent's ID is 221527 -- both are in the DRList lua

**Comment by wardz** [comment]
Imprision is an incapacitate and not a stun right? Only roots, taunts and stuns shows for mobs. I don't think incapacitate effect have DR in PvE unless they changed it in Shadowlands

**Comment by denumerable** [comment]
Right. It is an incap.

It definitely DRs. I can cast it 3x in a row and it goes from 60s to 30s to 15s.

**Comment by wardz** [comment]
Doesn't it have a 45s cooldown? DR reset time should only be 18 second unless there's some special edge case with Imprison to avoid making mobs perma immune with Detainment pvp talent. If that's the case, do you know how long the DR reset timer is for Imprison?

Does it only DR against quest bosses & elite mobs, or does it DR against normal mobs too?

**Comment by denumerable** [comment]
Imprison is a 45s cooldown. It lasts 60s, untalented. When it is PvP talented, it will only last 5-6 seconds.

It does NOT DR on normal mobs, but it does DR on quest mobs. I made a little video for you: https://www.twitch.tv/videos/904719751

**Comment by denumerable** [comment]
Thanks for checking on it -- learning new stuff about DRs ;)

**Comment by wardz** [comment]
Thanks too, that video was helpful. Will try and add a special timer for Imprison after the weekend.

**Comment by wardz** [comment]
Ok, I did some testing and it seems like that in Shadowlands every CC have a DR against special mobs (incap, disorients etc) so I added tracking for them all in v2.4.0. Against normal mobs it will still only show stuns and taunts like usual. Let me know if there's any issues with the new version and I'll fix it asap.
