### ISSUE TITLE
Request: Add anchor point option for Player DR to the “personal bar” UI element. 

### ISSUE THREAD

**Issue by denumerable** [wardz/Diminish#11]
This would be epic. I manually positioned it nearby the element but due to camera movement and such it doesn’t always stay in a nice place. Thanks @wardz.

**Comment by denumerable** [comment]
One more thing... your code and the add-on is so clean. It would be nice to see a better version of “nameplatecooldowns” — ever considered it?

https://github.com/casualshammy/NameplateCooldowns

**Comment by wardz** [comment]
Will look into it, shouldn't be hard to add.

I'm not interested in creating any more WoW addons sorry, I barely play anymore.

**Comment by wardz** [comment]
Added in v2.4.2.

**Comment by denumerable** [comment]
Thanks 🙏
