### ISSUE TITLE
Request: Add option to adjust font size/position for CC categories

### ISSUE THREAD

**Issue by Nukme** [wardz/Diminish#12]
**Is your feature request related to a problem?**
I'm on zhCN client and the font is too small to be readable on screen.

**Describe the solution or feature you'd like:**
I'm changing the hard-coded font size/position in _config.lua_ for now. I'd like to have a option to adjust the font size/position in-game.

**Additional context:**

**Comment by wardz** [comment]
Added an option for font size now. Options for positions will have to wait untill I recode the options panel, it's currently very bloated already.
