### ISSUE TITLE
Not able to see countdown text

### ISSUE THREAD

**Issue by BenjaminZ** [wardz/Diminish#14]
Version - 2.4.13

**What is the problem? Is there any Lua errors?**
Can't see the countdown text on the icons.

**Is this issue for Classic, TBC or Retail?**
TBC classic

**What steps will reproduce the problem?**
Can't see the countdown text no matter what configuration I've changed.

**Does the issue still occur when all addons except Diminish are disabled?**
Yes.

**Was it working in a previous version? If yes, which was the last good one?**
It has not been working since I've downloaded it but I can't remember when was that. I only noticed it when checking with my teammates and he mentioned there should be countdown texts.

**Any additional info? If you play on a non-english client, please include your locale type:**
I've been playing the EN client. I can see the indication numbers and the categories if I enable them.
![2021-10-30 10_04_42-Window](https://user-images.githubusercontent.com/7038898/139510152-a122ae19-8c0b-470a-a274-5619c812aa24.png)

**Comment by wardz** [comment]
That option only works if you have "Show Numbers for Cooldowns" enabled under WoW's interface actionbar options, or if you have an addon like OmniCC installed.

**Comment by BenjaminZ** [comment]
Thanks for help, it's resolved. :)
