### ISSUE TITLE
Tracking DR categories by default icon

### ISSUE THREAD

**Issue by Evolixe** [wardz/Diminish#21]
Just using this for feedback since thats what the first page link for feedback sends me to.

But eh, simple request really.. can we get an option to show DR categories not by using a text but rather by using a default set of icons based on the players currently played class?

What I mean is that I don't want a paladins HoJ to show up as a HoJ icon when im playing a Rogue, I want it to show as either a Cheap Shot or Kidney Shot icon. And for any DR school the players class has no access to a general icon can be used.. as long as it is the same one everytime. Same with Sheep and Sap, or Fear and Blind. Just to show the Sap icon for a Sheep and show the Blind icon for a Fear.

It makes no difference for veteran players, but for less experienced ones I think this is a major deal

**Comment by wardz** [comment]
It's kinda hidden/unclear but you can permanently select textures used for a DR category by right clicking one of the checkboxes listed under "Enabled Categories" in the addon options. If you also need seperate textures per character/class you can use the profile system under the addon options to achieve this aswell.

(For future reference, the addon is now in maintenance mode so any new features won't be added, other than bug fixes and new DR spell ids. Seems like I forgot to update the readme on Github, I'll merge it with the Curseforge one later.)
