### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RobertPinnock** [wardz/Diminish#23]
### What happened?

Not showing DRs on party frames (using raid frames), everything else seems to be working. Only started happening within the last week.

### Game Version

Retail

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

**Comment by wardz** [comment]
Reopening for now, noticed there's a bug in how the addon scans for raid/party frames which will sometimes make the DR icons not anchor to anything, which is prob what caused your issue in the first place.

**Comment by wardz** [comment]
Closing, should hopefully be fixed in v.2.5.1.
