### ISSUE TITLE
[Bug]:  Opener stuns not showing.

### ISSUE THREAD

**Issue by sidamakid** [wardz/Diminish#27]
### What happened?

Opener stun Diminishing returns aren't showing. If I use cheap shot. It doesn't appear on my nameplates on the Wotlk PTR.

### Game Version

The Burning Crusade Classic

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

### Any additional info?

No.

**Comment by wardz** [comment]
Wrath is not supported yet, will start working on it once i get beta access.

**Comment by wardz** [comment]
Added in v2.5.2.
