### ISSUE TITLE
[Bug]:  blocks GLadiusEx

### ISSUE THREAD

**Issue by aquila357** [wardz/Diminish#29]
### What happened?

Soon as i activate the newest version of Diminish. i cant use gladiusEx any longer. 
Do you have an idea whats the root-cause behind?
All other addons dont block it - just diminish. For Retail PvP thats huge.

### Game Version

Retail

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

**Comment by aquila357** [comment]
Fyi: i just tried it with v2.5.2 (version before current one) and there both add-ons work together without any issue

**Comment by wardz** [comment]
Should be fixed now in v2.5.4 i think, had some dragonflight spells added prematurely to DR data lib
