### ISSUE TITLE
Player DR's duplicating to party1

### ISSUE THREAD

**Issue by slawry00** [wardz/Diminish#31]
I'm using "anchor to UIParent" setting on party and player DR's and whenever my DR timer shows on player, it duplicates it to party1. Party1 will still track DR's actually cast on party1 and those won't duplicate to player, but anything on player will also go to party1 (and refresh as if it was applied to party1 directly). It also happens even when party1 doesn't exist.

I'm assuming this has to do with the fact that when not using "anchor to UIParent", that player is in the default raid frames. So that might be the source of the bug (unless I'm really missing something here).

![Diminish](https://user-images.githubusercontent.com/26912562/209917424-fa3cc74a-4ffa-4585-9249-92fc89620b14.gif)

**Comment by wardz** [comment]
Should be fixed now in v2.5.7 I think, if not just reopen ticket.
