### ISSUE TITLE
"Unleashed Shield" should not be a Root-DR

### ISSUE THREAD

**Issue by Rackelhardt** [wardz/Diminish#32]
### What happened?

There is a PvP Talent from Shaman, called "Unleashed Shield":

[https://www.wowhead.com/spell=356736/unleash-shield](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowhead.com%252fspell%253d356736%252funleash-shield)

Its like a kick-root (when both shields are active) but actually its NOT on the root DR.
Idk why they did it but it has its own DR.

In your Addon its in the root-DR-group. Would be great if you could remove it from there, because right now its it is very irritating when i play with actual roots like Earthgrab Totem, because the DR timer is always wrong.

### Game Version

Retail

### Game Language

German

### Does the issue still occur when all other addons are temporarily disabled?

None

**Comment by wardz** [comment]
Should be fixed now in v2.5.7, thanks.
