### ISSUE TITLE
Missing Spell ID in DRs

### ISSUE THREAD

**Issue by Bodify** [wardz/Diminish#38]
Warlocks have a talent called [Horrify](https://www.wowhead.com/spell=56244/horrify) that makes their fear just stand still.
This changes the fear spell id from [118699](https://www.wowhead.com/spell=130616) to [130616](https://www.wowhead.com/spell=130616/fear)

The new spell id is missing.

**Comment by wardz** [comment]
Thanks, should be fixed in v2.6.2.
