### ISSUE TITLE
Track only our DR ?

### ISSUE THREAD

**Issue by danielsawan** [wardz/Diminish#9]
Hi folks :)

I was wondering if it is possible to have a checkbox option that only track our own dr not our arena friend dr to ?
I mean i don't know all the class spell icon actually and when i see a dr that it not mine (without showing category) i can't even know from what school this dr come from. 

It would be very cool if when a friend start the dr cycle it instantly show my own spell that is impacted by the DR not his spell.

I hope it is clear enought... :p

**Comment by wardz** [comment]
You can manually chose what icon it uses for a DR category by **right clicking** the checkboxes under "Enabled Categories".

![WoWScrnShot_100420_063709](https://user-images.githubusercontent.com/10900212/95007137-7b1ffc00-060c-11eb-808e-b257885de1f2.jpg)

So for example if you're a Mage you can set the root category to use Frost Nova as an icon and it will always show Frost Nova even if Entangling Roots or some other spell is used. If you have trouble with knowing the categories I also recommend enabling "Display DR Category Label" on the main options page.

**Comment by danielsawan** [comment]
oh that's exactly what i was looking for
